### ISSUE TITLE
sqlite to postgresql (Windows + Docker)

### ISSUE THREAD

**Issue by FeckNeck** [dimitri/pgloader#1548]
I'm attempting to migrate a simple sqlite db file to postgresql with the following command :
```
docker run --rm -it dimitri/pgloader:latest pgloader F:\pgloader-test\test.db postgresql://example:example@host.docker.internal/example
```
The command seems to work since I have no errors as you can see from the image:
![image](https://github.com/dimitri/pgloader/assets/41020659/829543a7-776e-42c3-8fef-fcfe0c0d51c6)
I'm running postgresql throught Docker and here is my docker-compose.yml file :
```yaml
# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - 5432:5432
````
I've tried adding **--verbose**, **--debug**, **--type sqlite** and **sqlite:\\F:\pgloader-test.db** but it still doesn't work.
I thought the problem might be with the .db file I'm trying to migrate. So, tried exporting from [https://sqliteonline.com/](https://sqliteonline.com/) from the demo table's default config and it still doesn't work.  
I can connect to my postgres **example** database and create tables.  
I don't really understand where my error is coming from.
Thanks in advance for your help
